(********************************************************************
	@name Coq declarations for model
	@date 2020/11/16 16:20:11
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import examples.TT2BDD.BDD.


Definition InputModel : Model BDDMetamodel_EObject BDDMetamodel_ELink :=
	(Build_Model
		(
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment "700072760_Assignment" false)) :: 
		(Build_BDDMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1107730949_Leaf" ))) :: 
		(Build_BDDMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1461149300_Leaf" ))) :: 
		(Build_BDDMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1368594774_Subtree" ))) :: 
		(Build_BDDMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1371006431_Subtree" ))) :: 
		(Build_BDDMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "158453976_InputPort" "a"))) :: 
		(Build_BDDMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "726281927_Subtree" ))) :: 
		(Build_BDDMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "206835546_Leaf" ))) :: 
		(Build_BDDMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "413601558_Leaf" ))) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment "1658926803_Assignment" true)) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment "2075495587_Assignment" true)) :: 
		(Build_BDDMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "1447499999_InputPort" "b"))) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment "1652149987_Assignment" false)) :: 
		(Build_BDDMetamodel_EObject PortEClass (Build_Abstract_Port OutputPortEClass (BuildOutputPort "210652080_OutputPort" "s"))) :: 
		(Build_BDDMetamodel_EObject BDDEClass (BuildBDD "393040818_BDD" "Test")) :: 
		nil)
		(
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "700072760_Assignment" false)  (BuildOutputPort "210652080_OutputPort" "s"))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "700072760_Assignment" false)  (BuildLeaf "1461149300_Leaf" ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1107730949_Leaf" ) ( (BuildAssignment "1652149987_Assignment" false) :: nil ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1461149300_Leaf" ) ( (BuildAssignment "700072760_Assignment" false) :: nil ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1368594774_Subtree" )  (BuildInputPort "158453976_InputPort" "a"))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1368594774_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "726281927_Tree" ) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1368594774_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1371006431_Tree" ) ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1371006431_Subtree" )  (BuildInputPort "1447499999_InputPort" "b"))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1371006431_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "413601558_Tree" ) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1371006431_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1107730949_Tree" ) ))) ::
		(Build_BDDMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "158453976_InputPort" "a") ( (BuildSubtree "1368594774_Subtree" ) :: nil ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "726281927_Subtree" )  (BuildInputPort "1447499999_InputPort" "b"))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "726281927_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1461149300_Tree" ) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "726281927_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "206835546_Tree" ) ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "206835546_Leaf" ) ( (BuildAssignment "2075495587_Assignment" true) :: nil ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "413601558_Leaf" ) ( (BuildAssignment "1658926803_Assignment" true) :: nil ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "1658926803_Assignment" true)  (BuildOutputPort "210652080_OutputPort" "s"))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "1658926803_Assignment" true)  (BuildLeaf "413601558_Leaf" ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "2075495587_Assignment" true)  (BuildOutputPort "210652080_OutputPort" "s"))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "2075495587_Assignment" true)  (BuildLeaf "206835546_Leaf" ))) ::
		(Build_BDDMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "1447499999_InputPort" "b") ( (BuildSubtree "1371006431_Subtree" ) ::  (BuildSubtree "726281927_Subtree" ) :: nil ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "1652149987_Assignment" false)  (BuildOutputPort "210652080_OutputPort" "s"))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "1652149987_Assignment" false)  (BuildLeaf "1107730949_Leaf" ))) ::
		(Build_BDDMetamodel_ELink OutputPortAssignmentsEReference (BuildOutputPortAssignments  (BuildOutputPort "210652080_OutputPort" "s") ( (BuildAssignment "1652149987_Assignment" false) ::  (BuildAssignment "700072760_Assignment" false) ::  (BuildAssignment "1658926803_Assignment" true) ::  (BuildAssignment "2075495587_Assignment" true) :: nil ))) ::
		(Build_BDDMetamodel_ELink BDDPortsEReference (BuildBDDPorts  (BuildBDD "393040818_BDD" "Test") ( (Build_Abstract_Port InputPortEClass  (BuildInputPort "158453976_Port" "a") ) ::  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1447499999_Port" "b") ) ::  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "210652080_Port" "s") ) :: nil ))) ::
		(Build_BDDMetamodel_ELink BDDTreeEReference (BuildBDDTree  (BuildBDD "393040818_BDD" "Test")  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1368594774_Tree" ) ))) ::
		nil)
	).
