(********************************************************************
	@name Coq declarations for model
	@date 2020/10/28 15:29:22
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
 Require Import List.
 Require Import core.Model.
 Require Import String.
 Require Import examples.TT2BDD.TT.
 
 
 Definition InputModel : Model TTMetamodel_EObject TTMetamodel_ELink :=
     (Build_Model
         (
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "1147258851_InputPort" "" "a")))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "1691538257_Cell" "" false))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "1368594774_Cell" "" true))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement TruthTableEClass (BuildTruthTable "1146147158_TruthTable" "" "Test"))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement RowEClass (BuildRow "626742236_Row" ""))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "1931444790_Cell" "" false))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "158453976_Cell" "" false))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement PortEClass (Build_Abstract_Port OutputPortEClass (BuildOutputPort "2011482127_OutputPort" "" "s")))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "1800659519_Cell" "" false))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement RowEClass (BuildRow "459848100_Row" ""))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "726281927_Cell" "" true))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "577405636_Cell" "" true))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "1335505684_Cell" "" false))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "992768706_Cell" "" true))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "2145970759_Cell" "" true))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement RowEClass (BuildRow "905735620_Row" ""))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "891095110_InputPort" "" "b")))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "500772834_Cell" "" false))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement CellEClass (BuildCell "1226204845_Cell" "" true))) :: 
         (Build_TTMetamodel_EObject LocatedElementEClass (Build_Abstract_LocatedElement RowEClass (BuildRow "393040818_Row" ""))) :: 
         nil)
         (
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "1691538257_Cell" "" false)  (BuildRow "626742236_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "1691538257_Cell" "" false)  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "2011482127_Port" "" "s") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "1368594774_Cell" "" true)  (BuildRow "393040818_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "1368594774_Cell" "" true)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "891095110_Port" "" "b") ))) ::
         (Build_TTMetamodel_ELink TruthTablePortsEReference (BuildTruthTablePorts  (BuildTruthTable "1146147158_TruthTable" "" "Test") ( (Build_Abstract_Port InputPortEClass  (BuildInputPort "1147258851_Port" "" "a") ) ::  (Build_Abstract_Port InputPortEClass  (BuildInputPort "891095110_Port" "" "b") ) ::  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "2011482127_Port" "" "s") ) :: nil ))) ::
         (Build_TTMetamodel_ELink TruthTableRowsEReference (BuildTruthTableRows  (BuildTruthTable "1146147158_TruthTable" "" "Test") ( (BuildRow "905735620_Row" "") ::  (BuildRow "626742236_Row" "") ::  (BuildRow "459848100_Row" "") ::  (BuildRow "393040818_Row" "") :: nil ))) ::
         (Build_TTMetamodel_ELink RowOwnerEReference (BuildRowOwner  (BuildRow "626742236_Row" "")  (BuildTruthTable "1146147158_TruthTable" "" "Test"))) ::
         (Build_TTMetamodel_ELink RowCellsEReference (BuildRowCells  (BuildRow "626742236_Row" "") ( (BuildCell "500772834_Cell" "" false) ::  (BuildCell "1800659519_Cell" "" false) ::  (BuildCell "1691538257_Cell" "" false) :: nil ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "1931444790_Cell" "" false)  (BuildRow "905735620_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "1931444790_Cell" "" false)  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "2011482127_Port" "" "s") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "158453976_Cell" "" false)  (BuildRow "393040818_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "158453976_Cell" "" false)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1147258851_Port" "" "a") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "1800659519_Cell" "" false)  (BuildRow "626742236_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "1800659519_Cell" "" false)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "891095110_Port" "" "b") ))) ::
         (Build_TTMetamodel_ELink RowOwnerEReference (BuildRowOwner  (BuildRow "459848100_Row" "")  (BuildTruthTable "1146147158_TruthTable" "" "Test"))) ::
         (Build_TTMetamodel_ELink RowCellsEReference (BuildRowCells  (BuildRow "459848100_Row" "") ( (BuildCell "1335505684_Cell" "" false) ::  (BuildCell "992768706_Cell" "" true) ::  (BuildCell "1226204845_Cell" "" true) :: nil ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "726281927_Cell" "" true)  (BuildRow "393040818_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "726281927_Cell" "" true)  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "2011482127_Port" "" "s") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "577405636_Cell" "" true)  (BuildRow "905735620_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "577405636_Cell" "" true)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "891095110_Port" "" "b") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "1335505684_Cell" "" false)  (BuildRow "459848100_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "1335505684_Cell" "" false)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1147258851_Port" "" "a") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "992768706_Cell" "" true)  (BuildRow "459848100_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "992768706_Cell" "" true)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "891095110_Port" "" "b") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "2145970759_Cell" "" true)  (BuildRow "905735620_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "2145970759_Cell" "" true)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1147258851_Port" "" "a") ))) ::
         (Build_TTMetamodel_ELink RowOwnerEReference (BuildRowOwner  (BuildRow "905735620_Row" "")  (BuildTruthTable "1146147158_TruthTable" "" "Test"))) ::
         (Build_TTMetamodel_ELink RowCellsEReference (BuildRowCells  (BuildRow "905735620_Row" "") ( (BuildCell "2145970759_Cell" "" true) ::  (BuildCell "577405636_Cell" "" true) ::  (BuildCell "1931444790_Cell" "" false) :: nil ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "500772834_Cell" "" false)  (BuildRow "626742236_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "500772834_Cell" "" false)  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1147258851_Port" "" "a") ))) ::
         (Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner  (BuildCell "1226204845_Cell" "" true)  (BuildRow "459848100_Row" ""))) ::
         (Build_TTMetamodel_ELink CellPortEReference (BuildCellPort  (BuildCell "1226204845_Cell" "" true)  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "2011482127_Port" "" "s") ))) ::
         (Build_TTMetamodel_ELink RowOwnerEReference (BuildRowOwner  (BuildRow "393040818_Row" "")  (BuildTruthTable "1146147158_TruthTable" "" "Test"))) ::
         (Build_TTMetamodel_ELink RowCellsEReference (BuildRowCells  (BuildRow "393040818_Row" "") ( (BuildCell "158453976_Cell" "" false) ::  (BuildCell "1368594774_Cell" "" true) ::  (BuildCell "726281927_Cell" "" true) :: nil ))) ::
         nil)
     ).
 