(********************************************************************
	@name Coq declarations for model
	@date 2020/11/16 18:54:48
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import examples.TT2BDD.BDDv2.


Definition InputModel : Model bddMetamodel_EObject bddMetamodel_ELink :=
	(Build_Model
		(
			(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1691538257_Subtree" ))) :: 
			(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1368594774_Leaf" ))) :: 
			(Build_bddMetamodel_EObject BDDEClass (BuildBDD "626742236_BDD" "Test")) :: 
			(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "1371006431_Assignment" true)) :: 
			(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "158453976_Assignment" false)) :: 
			(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1800659519_Subtree" ))) :: 
			(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "459848100_InputPort" "b"))) :: 
			(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "726281927_Assignment" false)) :: 
			(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1335505684_Subtree" ))) :: 
			(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "992768706_Leaf" ))) :: 
			(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "413601558_Leaf" ))) :: 
			(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1447499999_Leaf" ))) :: 
			(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "500772834_InputPort" "a"))) :: 
			(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "1226204845_Assignment" true)) :: 
			(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port OutputPortEClass (BuildOutputPort "393040818_OutputPort" "s"))) :: 
			nil
		)
		(
			(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1691538257_Subtree" )  (BuildInputPort "459848100_InputPort" "b"))) ::
			(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1691538257_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1447499999_Tree" ) ))) ::
			(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1691538257_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "413601558_Tree" ) ))) ::
			(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1368594774_Leaf" ) ( (BuildAssignment "158453976_Assignment" false) :: nil ))) ::
			(Build_bddMetamodel_ELink BDDPortsEReference (BuildBDDPorts  (BuildBDD "626742236_BDD" "Test") ( (Build_Abstract_Port InputPortEClass  (BuildInputPort "500772834_Port" "a") ) ::  (Build_Abstract_Port InputPortEClass  (BuildInputPort "459848100_Port" "b") ) ::  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "393040818_Port" "s") ) :: nil ))) ::
			(Build_bddMetamodel_ELink BDDTreeEReference (BuildBDDTree  (BuildBDD "626742236_BDD" "Test")  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1800659519_Tree" ) ))) ::
			(Build_bddMetamodel_ELink BDDTreesEReference (BuildBDDTrees  (BuildBDD "626742236_BDD" "Test") ( :: nil ))) ::
			(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "1371006431_Assignment" true)  (BuildOutputPort "393040818_OutputPort" "s"))) ::
			(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "1371006431_Assignment" true)  (BuildLeaf "413601558_Leaf" ))) ::
			(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "158453976_Assignment" false)  (BuildOutputPort "393040818_OutputPort" "s"))) ::
			(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "158453976_Assignment" false)  (BuildLeaf "1368594774_Leaf" ))) ::
			(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1800659519_Subtree" )  (BuildInputPort "500772834_InputPort" "a"))) ::
			(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1800659519_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1691538257_Tree" ) ))) ::
			(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1800659519_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1335505684_Tree" ) ))) ::
			(Build_bddMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "459848100_InputPort" "b") ( (BuildSubtree "1335505684_Subtree" ) ::  (BuildSubtree "1691538257_Subtree" ) :: nil ))) ::
			(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "726281927_Assignment" false)  (BuildOutputPort "393040818_OutputPort" "s"))) ::
			(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "726281927_Assignment" false)  (BuildLeaf "1447499999_Leaf" ))) ::
			(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1335505684_Subtree" )  (BuildInputPort "459848100_InputPort" "b"))) ::
			(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1335505684_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "992768706_Tree" ) ))) ::
			(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1335505684_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1368594774_Tree" ) ))) ::
			(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "992768706_Leaf" ) ( (BuildAssignment "1226204845_Assignment" true) :: nil ))) ::
			(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "413601558_Leaf" ) ( (BuildAssignment "1371006431_Assignment" true) :: nil ))) ::
			(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1447499999_Leaf" ) ( (BuildAssignment "726281927_Assignment" false) :: nil ))) ::
			(Build_bddMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "500772834_InputPort" "a") ( (BuildSubtree "1800659519_Subtree" ) :: nil ))) ::
			(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "1226204845_Assignment" true)  (BuildOutputPort "393040818_OutputPort" "s"))) ::
			(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "1226204845_Assignment" true)  (BuildLeaf "992768706_Leaf" ))) ::
			(Build_bddMetamodel_ELink OutputPortAssignmentsEReference (BuildOutputPortAssignments  (BuildOutputPort "393040818_OutputPort" "s") ( (BuildAssignment "158453976_Assignment" false) ::  (BuildAssignment "726281927_Assignment" false) ::  (BuildAssignment "1226204845_Assignment" true) ::  (BuildAssignment "1371006431_Assignment" true) :: nil ))) ::
			nil
		)
	).
